### ISSUE TITLE
Cannot read property 'camera' of null

### ISSUE THREAD

**Issue by Magi1053** [WebGL-Map/glm-client#3]
![image](https://user-images.githubusercontent.com/1045179/63212402-a6beea80-c0c9-11e9-8fc2-2a0796613091.png)

**Comment by tylerbucher** [comment]
I apologize for the late reply (for some reason GitHub did not notify me of a new open issue). Did you download the client from here https://github.com/WebGL-Map/glm-client/releases or did you compile it from the sources?
